---
title: "Assignment_2"
author: "Clara Ferrer Castellà"
date: "4 de mayo de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Before start:

* Clean the Environment
```{r}
rm(list=ls())
```

* Load Packages
```{r}

library("ggplot2")
library("grid")
library("gridExtra")
library("scales")
library("plyr")
library("corrplot")
library("gbm")
library("caret")
library("tidyr")
library("dplyr")
library("unbalanced")

```


* Functions definition
```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


* Set path and load the data
```{r}
# Stablishing the working directory and the file paths 
Working_directory <- setwd("~/DM_Basic_Assignment/Assignment_2")
d <- unzip("Assignment2_data.zip")
file_training <- file.path(Working_directory, "Data Mining VU data" , "training_set_VU_DM_2014.csv")
file_test <- file.path(Working_directory, "Data Mining VU data" , "test_set_VU_DM_2014.csv")



# Opening the files 
all_train <- read.csv(file_training, header = TRUE)
#test <- read.csv(file_test, header = TRUE)


```


##Visualize the Data

* Visualization of the NA Data of the new hotels 

```{r}
# Change the NAs to character to be taken into account in the plot
all_train$prop_review_score[is.na(all_train$prop_review_score)] <- "NA"

# Plot of the Hotel rating score for all hotels
p1 <- ggplot(all_train, aes(x=prop_review_score)) + geom_bar() + ggtitle("A") + xlab("Hotel Review Score")

# Plot of the score of the booked hotels, to see if the users prefer a new hotel (NA) or a hotel with the woorst case scenario (0)
pre_NA_visual <-table(Rating=all_train$prop_review_score, Booked= as.logical(all_train$booking_bool))
pre_NA_visual <- as.data.frame(prop.table(pre_NA_visual, 1)) # row percentages 
NA_visual <- pre_NA_visual[pre_NA_visual$Rating=="NA"| pre_NA_visual$Rating=="0",]
NA_visual <- NA_visual[NA_visual$Booked==TRUE,]

p2 <- ggplot(NA_visual, aes(x = Rating, y = Freq)) + 
  geom_bar(stat = "identity", position = position_dodge()) + 
  ggtitle("B") + xlab("Hotel Review Score")

multiplot(p1, p2, cols=2)

# Remove useless Data from Environment
rm(NA_visual, p1, p2, pre_NA_visual)
```



* Visualization of the unbalanced data
```{r}
# Create the ignored column
all_train$ignored_bool <- ifelse(all_train$click_bool == 0 & all_train$booking_bool == 0, 1, 0)

balance_visual <- data.frame(Type = c("click","book", "ignored"), Value=c(sum(all_train$click_bool==1), sum(all_train$booking_bool==1), sum(all_train$ignored_bool==1)))

ggplot(balance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity")

# balance_visual <- data.frame(Yes=c(sum(train$click_bool==1), sum(train$booking_bool==1), sum(train$ignored_bool==0)), No = c(sum(train$click_bool==0), sum(train$booking_bool==0), sum(train$ignored_bool==1)), row.names = c("click","book", "ignored"))
# 
# balance_visual <- as.matrix(balance_visual)
# balance_visual <- as.table(balance_visual)
# 
# percentage_balance <- as.data.frame(prop.table(balance_visual, 1)*100) # row percentages 
# 
# 
# ggplot(percentage_balance, aes(x = Var2, y = Freq, fill = Var1)) + 
#   geom_bar(stat = "identity", position = position_dodge())

# Remove useless Data from Environment
rm(balance_visual,NA_visual,pre_NA_visual)
```


##Split of the data 
```{r}
#Group by search ID to then split the test set
all_train <- all_train %>%
  group_by(srch_id)

#Split of the test set
all_length <- nrow(all_train)
splity <- all_length*0.15
test <- all_train[1:splity,]
splited_train <- all_train[(splity+1):all_length,]
# Modify number of cucus depending on the srch_id cutoff
rm(all_train) 

#Split the validation set
dt <- sort(sample(nrow(splited_train), nrow(splited_train)*.82353)) #to have 15% of the real_train
train <- splited_train[dt,]
validation <- splited_train[-dt,]

# Remove useless Data from Environment
rm(splited_train, dt)
rm(splity, all_length)
```



# Data Balance 
```{r}

# Balance the Train
train$ignored_bool <- ifelse(train$click_bool == 0 & train$booking_bool == 0, 0, 1) # Change previous 1 to 0, then this will be changed again, it's only in order to be able to run the function ubBalance()

output <- as.factor(train$ignored_bool) 
input <- train

data <- ubBalance(X=input, Y=output, type = "ubUnder", perc = 40) #apply undersampling
underTrain <- data.frame(data$X) #undersampled dataset





#Visualizations to compare data unbalanced and balanced
unbalance_visual <- data.frame(Type = c("Click","Book", "Ignored"), Value=c(sum(train$click_bool==1), sum(train$booking_bool==1), sum(train$ignored_bool==0)))

p1 <- ggplot(unbalance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity", show.legend = FALSE) +
  ggtitle("Unbalanced Data")

balance_visual <- data.frame(Type = c("Click","Book", "Ignored"), Value=c(sum(underTrain$click_bool==1), sum(underTrain$booking_bool==1), sum(underTrain$ignored_bool==0)))  # We'll only do one plot since it's already representative of how the other splits(validation and test) are balanced. 

p2 <- ggplot(balance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity", show.legend = FALSE) +
  ggtitle("Balanced Data")

multiplot(p1, p2, cols=2)





# Validation Balance 
validation$ignored_bool <- ifelse(validation$click_bool == 0 & validation$booking_bool == 0, 0, 1) # Change previous 1 to 0, then this will be changed again, it's only in order to be able to run the function ubBalance()
output <- as.factor(validation$ignored_bool) 
input <- validation

data <- ubBalance(X=input, Y=output, type = "ubUnder", perc = 40) #apply undersampling
underValidation <- data.frame(data$X) #undersampled dataset





# Test Balance
test$ignored_bool <- ifelse(test$click_bool == 0 & test$booking_bool == 0, 0, 1) # Change previous 1 to 0, then this will be changed again, it's only in order to be able to run the function ubBalance()
output <- as.factor(test$ignored_bool) 
input <- test

data <- ubBalance(X=input, Y=output, type = "ubUnder", perc = 40) #apply undersampling
underTest <- data.frame(data$X) #undersampled dataset





# Remove useless Data from Envirinment
rm(balance_visual, data, input, unbalance_visual, p1, p2, output, train, validation, test)





# Change values 0 to 1 of the "ignored_bool" variable in the new balanced data sets
underTrain$ignored_bool <- ifelse(underTrain$click_bool == 0 & underTrain$booking_bool == 0, 1, 0) 
underTest$ignored_bool <- ifelse(underTest$click_bool == 0 & underTest$booking_bool == 0, 1, 0) 
underValidation$ignored_bool <- ifelse(underValidation$click_bool == 0 & underValidation$booking_bool == 0, 1, 0)





# Create csv files of the balanced data sets (underTrain, underTest, underValidation)

write.csv(underTrain, file = "underTrain.csv", col.names = TRUE, row.names=FALSE)
write.csv(underTest, file = "underTest.csv", col.names = TRUE, row.names=FALSE)
write.csv(underValidation, file = "underValidation.csv", col.names = TRUE, row.names=FALSE)





```




# Set path and load the balanced data sets (underTrain, underTest, underValidation)
```{r}

file_underTrain <- file.path(Working_directory, "underTrain.csv")
underTrain <- read.csv(file_underTrain, header = TRUE)

file_underTest <- file.path(Working_directory, "underTest.csv")
underTest <- read.csv(file_underTest, header = TRUE)

file_underValidatioin <- file.path(Working_directory, "underValidation.csv")
underValidation <- read.csv(file_underValidatioin, header = TRUE)

```

